// apps/demo-angular/src/app/app.component.ts
import { Component } from '@angular/core'

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'demo-angular'
}

<main>
  <section>
    <h1>App Angular</h1>
  </section>

  <section>
    <h2>Stencil Components</h2>
    <div class="component-row">
      <!-- <my-button />
      <my-button /><my-button /><my-button /><my-button /><my-button /><my-button /> -->
    </div>
  </section>
</main>

<router-outlet></router-outlet>

// apps/demo-react/src/App.tsx
import './App.css'
import { defineCustomElements } from 'ui-stencil-react'

void defineCustomElements()

function App() {
  return (
    <>
      <main>
        <section>
          <h1>App React</h1>
        </section>

        <section>
          <h2>Stencil Components</h2>
          <div className="component-row">{/* <MyButton></MyButton> */}</div>
        </section>
      </main>
    </>
  )
}

export default App
